//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDVDs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.Discs = new HashSet<Disc>();
        }
    
        public int Id { get; set; }
        public int CaseNumber { get; set; }
        public string CaseType { get; set; }
        public int TotalDiscs { get; set; }
        public string Notes { get; set; }
        public bool IsABoxset { get; set; }
        public string Title { get; set; }
        public int StorageBoxId { get; set; }
        public int DVDIconId { get; set; }
    
        public virtual ICollection<Disc> Discs { get; set; }
        public virtual DVDIcon DVDIcon { get; set; }
        public virtual StorageBox StorageBox { get; set; }
    }
}
