//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDVDs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public int ContentNumber { get; set; }
        public string Notes { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string Cast { get; set; }
        public string Director { get; set; }
        public int DiscId { get; set; }
        public int GenreId { get; set; }
        public int RatingId { get; set; }
        public int DVDIconId { get; set; }
    
        public virtual Disc Disc { get; set; }
        public virtual DVDIcon DVDIcon { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
