//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDVDs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDVDsContext : DbContext
    {
        public MyDVDsContext()
            : base("name=MyDVDsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Case> Cases { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Disc> Discs { get; set; }
        public DbSet<DVDIcon> DVDIcons { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<StorageBox> StorageBoxes { get; set; }
    }
}
