//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDVDs
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageBox
    {
        public StorageBox()
        {
            this.Cases = new HashSet<Case>();
        }
    
        public int Id { get; set; }
        public int BoxNumber { get; set; }
        public string BoxType { get; set; }
        public int TotalCases { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
    }
}
